require "rubygems"
require "bundler"
Bundler.setup

desc "Builds the site"
task :build do
  puts "- Building the site"
  system "staticmatic build ."
  
  puts "- Remove old build from web_py"
  system "rm ../web_py/index.html"
  system "rm -rf ../web_py/stylesheets"
  
  puts "- Copy new build from web_py"
  system "cp -R site/index.html ../web_py/"
  system "cp -R site/stylesheets ../web_py/"
end